/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * TestDefinition
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-02T14:44:36.831Z")
public class TestDefinition {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("author")
  private String author = null;

  @SerializedName("terminationReason")
  private String terminationReason = null;

  @SerializedName("lgCount")
  private Integer lgCount = null;

  @SerializedName("project")
  private String project = null;

  @SerializedName("scenario")
  private String scenario = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("qualityStatus")
  private String qualityStatus = null;

  @SerializedName("startDate")
  private Long startDate = null;

  @SerializedName("endDate")
  private Long endDate = null;

  @SerializedName("duration")
  private Long duration = null;

  public TestDefinition id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the test.
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier of the test.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TestDefinition name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the test.
   * @return name
  **/
  @ApiModelProperty(value = "Name of the test.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TestDefinition description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the test.
   * @return description
  **/
  @ApiModelProperty(value = "Description of the test.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TestDefinition author(String author) {
    this.author = author;
    return this;
  }

   /**
   * First and Last name of the person who launched the test.
   * @return author
  **/
  @ApiModelProperty(value = "First and Last name of the person who launched the test.")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public TestDefinition terminationReason(String terminationReason) {
    this.terminationReason = terminationReason;
    return this;
  }

   /**
   * Reason that caused the test to end. It can be: POLICY, VARIABLE, MANUAL, LG_AVAILABILITY, LICENSE, UNKNOWN.
   * @return terminationReason
  **/
  @ApiModelProperty(value = "Reason that caused the test to end. It can be: POLICY, VARIABLE, MANUAL, LG_AVAILABILITY, LICENSE, UNKNOWN.")
  public String getTerminationReason() {
    return terminationReason;
  }

  public void setTerminationReason(String terminationReason) {
    this.terminationReason = terminationReason;
  }

  public TestDefinition lgCount(Integer lgCount) {
    this.lgCount = lgCount;
    return this;
  }

   /**
   * Total number of Load Generators used in the test.
   * @return lgCount
  **/
  @ApiModelProperty(value = "Total number of Load Generators used in the test.")
  public Integer getLgCount() {
    return lgCount;
  }

  public void setLgCount(Integer lgCount) {
    this.lgCount = lgCount;
  }

  public TestDefinition project(String project) {
    this.project = project;
    return this;
  }

   /**
   * Name of the project.
   * @return project
  **/
  @ApiModelProperty(value = "Name of the project.")
  public String getProject() {
    return project;
  }

  public void setProject(String project) {
    this.project = project;
  }

  public TestDefinition scenario(String scenario) {
    this.scenario = scenario;
    return this;
  }

   /**
   * Name of the scenario.
   * @return scenario
  **/
  @ApiModelProperty(value = "Name of the scenario.")
  public String getScenario() {
    return scenario;
  }

  public void setScenario(String scenario) {
    this.scenario = scenario;
  }

  public TestDefinition status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the test. It can be: STARTING, RUNNING, TERMINATED, UNKNOWN.
   * @return status
  **/
  @ApiModelProperty(value = "Status of the test. It can be: STARTING, RUNNING, TERMINATED, UNKNOWN.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public TestDefinition qualityStatus(String qualityStatus) {
    this.qualityStatus = qualityStatus;
    return this;
  }

   /**
   * Quality status of the test. It can be: PASSED, FAILED, COMPUTING, UNKNOWN.
   * @return qualityStatus
  **/
  @ApiModelProperty(value = "Quality status of the test. It can be: PASSED, FAILED, COMPUTING, UNKNOWN.")
  public String getQualityStatus() {
    return qualityStatus;
  }

  public void setQualityStatus(String qualityStatus) {
    this.qualityStatus = qualityStatus;
  }

  public TestDefinition startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Timestamp when the test started.
   * @return startDate
  **/
  @ApiModelProperty(value = "Timestamp when the test started.")
  public Long getStartDate() {
    return startDate;
  }

  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  public TestDefinition endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Timestamp when the test ended.
   * @return endDate
  **/
  @ApiModelProperty(value = "Timestamp when the test ended.")
  public Long getEndDate() {
    return endDate;
  }

  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  public TestDefinition duration(Long duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Test duration in seconds.
   * @return duration
  **/
  @ApiModelProperty(value = "Test duration in seconds.")
  public Long getDuration() {
    return duration;
  }

  public void setDuration(Long duration) {
    this.duration = duration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestDefinition testDefinition = (TestDefinition) o;
    return Objects.equals(this.id, testDefinition.id) &&
        Objects.equals(this.name, testDefinition.name) &&
        Objects.equals(this.description, testDefinition.description) &&
        Objects.equals(this.author, testDefinition.author) &&
        Objects.equals(this.terminationReason, testDefinition.terminationReason) &&
        Objects.equals(this.lgCount, testDefinition.lgCount) &&
        Objects.equals(this.project, testDefinition.project) &&
        Objects.equals(this.scenario, testDefinition.scenario) &&
        Objects.equals(this.status, testDefinition.status) &&
        Objects.equals(this.qualityStatus, testDefinition.qualityStatus) &&
        Objects.equals(this.startDate, testDefinition.startDate) &&
        Objects.equals(this.endDate, testDefinition.endDate) &&
        Objects.equals(this.duration, testDefinition.duration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, author, terminationReason, lgCount, project, scenario, status, qualityStatus, startDate, endDate, duration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestDefinition {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    terminationReason: ").append(toIndentedString(terminationReason)).append("\n");
    sb.append("    lgCount: ").append(toIndentedString(lgCount)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    scenario: ").append(toIndentedString(scenario)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    qualityStatus: ").append(toIndentedString(qualityStatus)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

